---
- import_role:
    name: kubernetes.containerruntime
    tasks_from: check_containerd.yaml
  when: runtime_engine == "containerd"

- import_role:
    name: kubernetes.containerruntime
    tasks_from: check_crio.yaml
  when: runtime_engine == "cri-o"
