---
- name: Check crictl info dump
  shell: "crictl info"
  become: yes
  args:
    executable: "/bin/bash"
  register: crictl_output
  failed_when: false
  changed_when: false

- name: Trigger restart of cri-o service
  debug:
    msg: "A restart is needed"
  when: crictl_output.rc != 0
  notify:
    - Restart crio
