---
- name: Installing Kubernetes
  tags: packages
  gather_facts: true
  hosts: workers
  roles:
    - variables
  tasks:
    - import_role:
        name: kubernetes.common

- name: Determining Bootstrap Node
  hosts: controlplanes
  tags: join,workers
  tasks:
    - set_fact:
        control_plane_nodes: "{{ hostvars|dict2items|selectattr('value.group_names','search','controlplanes')|map(attribute='key') }}"
      run_once: true

    - name: Register Bootstrap
      add_host:
        name: "{{ control_plane_nodes[0] }}"
        groups: bootstrap
      when: "ansible_host == control_plane_nodes[0]"
      changed_when: false

- name: Generate Join Facts
  hosts: bootstrap
  tags: workers
  roles:
    - variables
  tasks:
    - import_role:
        name: kubernetes.worker
        tasks_from: generate_join.yaml

- name: Join Worker Nodes
  serial: 1
  hosts: workers
  tags: workers
  roles:
    - variables
  tasks:
    - import_role:
        name: kubernetes.worker
        tasks_from: join.yaml

- name: Applying node labels to Worker Nodes
  hosts: workers
  tags: bootstrap,controlplanes,workers
  roles:
    - variables
  tasks:
    - import_role:
        name: kubernetes.worker
        tasks_from: apply_labels.yaml
